# Generated by Django 3.2.6 on 2021-10-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211006_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_login',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.emp_reg'),
        ),
        migrations.AlterField(
            model_name='emp_login',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
